CREATE TABLE IF NOT EXISTS `member` (
    member_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    name VARCHAR(15) NOT NULL,
    age SMALLINT NULL,
    profile_id SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS post_category (
    category_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS post (
    post_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id SMALLINT NOT NULL,
    member_id BIGINT NOT NULL,
    title VARCHAR(63) NOT NULL,
    content TEXT NOT NULL,
    views SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_post_member FOREIGN KEY (member_id) REFERENCES `member`(member_id),
    CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES post_category(category_id)
);

CREATE INDEX idx_post_list ON post (deleted_at, post_id);
